#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_SAMSUNG_S6SY761) += S6SY761/
obj-$(CONFIG_TOUCHPANEL_SAMSUNG) += sec_common.o

#endif
