# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSOR_HALL_MXM1120)	+=  hall_mxm1120_up.o hall_mxm1120_down.o 

#obj-y 	+= mxm1120_up.o mxm1120_down.o
#mxm1120_down.o



