#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S3508) += S3508/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S3320) += S3320/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S3706) += S3706/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S4322) += S4322/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4310) += TD4310/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S1302) += S1302_virtal_key/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TCM) += Syna_tcm/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_touch_panel_remote.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_common.o

#endif
